In [25]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\archive (1)\Assignment-1_Data.csv", sep = ";")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20744\972729250.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\ASUS\Downloads\archive (1)\Assignment-1_Data.csv", sep = ";")

In [27]:
df.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,01.12.2010 08:26,"2,55",17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,01.12.2010 08:26,"2,75",17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522064 entries, 0 to 522063
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   BillNo      522064 non-null  object
 1   Itemname    520609 non-null  object
 2   Quantity    522064 non-null  int64
 3   Date        522064 non-null  object
 4   Price       522064 non-null  object
 5   CustomerID  388023 non-null  float64
 6   Country     522064 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 27.9+ MB

In [29]:
df["Price"] = df["Price"].str.replace(",", ".").astype(float)

In [30]:
df["Date"] = pd.to_datetime(df["Date"], format="%d.%m.%Y %H:%M")

In [31]:
df.isnull().sum()

BillNo             0
Itemname        1455
Quantity           0
Date               0
Price              0
CustomerID    134041
Country            0
dtype: int64

In [32]:
duplicate = df[df.duplicated(keep=False)].sort_values(["Itemname", "BillNo"]).head(20)
duplicate

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
361052,569424,12 COLOURED PARTY BALLOONS,10,2011-10-04 10:49:00,0.65,15529.0,United Kingdom
361053,569424,12 COLOURED PARTY BALLOONS,10,2011-10-04 10:49:00,0.65,15529.0,United Kingdom
361054,569424,12 COLOURED PARTY BALLOONS,10,2011-10-04 10:49:00,0.65,15529.0,United Kingdom
385095,571372,12 COLOURED PARTY BALLOONS,1,2011-10-17 11:55:00,0.65,17201.0,United Kingdom
385120,571372,12 COLOURED PARTY BALLOONS,1,2011-10-17 11:55:00,0.65,17201.0,United Kingdom
556,536412,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
569,536412,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
589,536412,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
592,536412,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
595,536412,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
487174,579124,12 HANGING EGGS HAND PAINTED,1,2011-11-28 12:14:00,2.08,15721.0,United Kingdom
487205,579124,12 HANGING EGGS HAND PAINTED,1,2011-11-28 12:14:00,2.08,15721.0,United Kingdom
514490,581134,12 HANGING EGGS HAND PAINTED,1,2011-12-07 13:12:00,2.08,16368.0,United Kingdom
514501,581134,12 HANGING EGGS HAND PAINTED,1,2011-12-07 13:12:00,2.08,16368.0,United Kingdom
4515,536796,12 MESSAGE CARDS WITH ENVELOPES,1,2010-12-02 15:46:00,1.65,15574.0,United Kingdom
4575,536796,12 MESSAGE CARDS WITH ENVELOPES,1,2010-12-02 15:46:00,1.65,15574.0,United Kingdom
176889,552652,12 MESSAGE CARDS WITH ENVELOPES,1,2011-05-10 14:09:00,1.65,14591.0,United Kingdom
176902,552652,12 MESSAGE CARDS WITH ENVELOPES,1,2011-05-10 14:09:00,1.65,14591.0,United Kingdom
220122,556915,12 MESSAGE CARDS WITH ENVELOPES,1,2011-06-15 13:35:00,1.65,15036.0,United Kingdom
220144,556915,12 MESSAGE CARDS WITH ENVELOPES,1,2011-06-15 13:35:00,1.65,15036.0,United Kingdom

In [33]:
df = df.drop(duplicate.index)

In [34]:
df[df["CustomerID"].isna()][["BillNo", "CustomerID"]]

        BillNo  CustomerID
613     536414         NaN
1410    536544         NaN
1411    536544         NaN
1412    536544         NaN
1413    536544         NaN
...        ...         ...
521695  581498         NaN
521696  581498         NaN
521697  581498         NaN
521698  581498         NaN
521699  581498         NaN

[134041 rows x 2 columns]

In [35]:
df[df["Price"] == 0]

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
613,536414,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1937,536545,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1938,536546,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1939,536547,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1940,536549,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...
517266,581234,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
518770,581406,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
518771,581406,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
518820,581408,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
519172,581422,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [36]:
df.describe()

,Quantity,Date,Price,CustomerID
count,522044.000000,522044,522044.000000,388003.000000
mean,10.090726,2011-07-04 12:52:53.320218368,3.826891,15316.883179
min,-9600.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 10:15:00,1.250000,13950.000000
50%,3.000000,2011-07-20 08:59:00,2.080000,15265.000000
75%,10.000000,2011-10-19 14:12:00,4.130000,16837.000000
max,80995.000000,2011-12-09 12:50:00,13541.330000,18287.000000
std,161.113603,NaN,41.901399,1721.857667

In [37]:
max_id = df["CustomerID"].max()
null_bills = df.loc[df["CustomerID"].isna(), "BillNo"].unique()
new_ids = range(int(max_id) + 1, int(max_id) + 1 + len(null_bills))
bill_to_customer = dict(zip(null_bills, new_ids))
df.loc[df["CustomerID"].isna(), "CustomerID"] = df.loc[df["CustomerID"].isna(), "BillNo"].map(bill_to_customer)
df["CustomerID"] = df["CustomerID"].astype(int)

In [38]:
df.loc[df["CustomerID"] > max_id] \
.sort_values(["CustomerID", "BillNo"])

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
613,536414,NaN,56,2010-12-01 11:52:00,0.00,18288,United Kingdom
1410,536544,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,18289,United Kingdom
1411,536544,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,18289,United Kingdom
1412,536544,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,18289,United Kingdom
1413,536544,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,18289,United Kingdom
...,...,...,...,...,...,...,...
521695,581498,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,21787,United Kingdom
521696,581498,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,21787,United Kingdom
521697,581498,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,21787,United Kingdom
521698,581498,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,21787,United Kingdom
521699,581498,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,21787,United Kingdom

In [39]:
bill_na = df[df["Itemname"].isna()]
bill_na['Price'].unique()

array([0.])

In [40]:
df = df.dropna(subset=["Itemname"])
df.isna().sum()

BillNo        0
Itemname      0
Quantity      0
Date          0
Price         0
CustomerID    0
Country       0
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 520589 entries, 0 to 522063
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   BillNo      520589 non-null  object
 1   Itemname    520589 non-null  object
 2   Quantity    520589 non-null  int64
 3   Date        520589 non-null  datetime64[ns]
 4   Price       520589 non-null  float64
 5   CustomerID  520589 non-null  int64
 6   Country     520589 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.8+ MB

In [42]:
df[~df["Itemname"].str.isupper()]

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
473,536408,BAG 500g SWIRLY MARBLES,12,2010-12-01 11:41:00,1.65,14307,United Kingdom
909,536500,POLYESTER FILLER PAD 45x45cm,10,2010-12-01 12:35:00,1.55,17377,United Kingdom
1928,536544,BAG 125g SWIRLY MARBLES,1,2010-12-01 14:32:00,0.85,18289,United Kingdom
1929,536544,BAG 250g SWIRLY MARBLES,1,2010-12-01 14:32:00,1.66,18289,United Kingdom
1991,536557,POLYESTER FILLER PAD 45x30cm,2,2010-12-01 14:41:00,1.45,17841,United Kingdom
...,...,...,...,...,...,...,...
520812,581492,BAG 125g SWIRLY MARBLES,1,2011-12-09 10:03:00,0.83,21785,United Kingdom
520813,581492,BAG 250g SWIRLY MARBLES,1,2011-12-09 10:03:00,1.63,21785,United Kingdom
521213,581492,3 TRADITIONAl BISCUIT CUTTERS SET,1,2011-12-09 10:03:00,4.13,21785,United Kingdom
521770,581514,BAG 500g SWIRLY MARBLES,84,2011-12-09 11:20:00,0.39,17754,United Kingdom
521773,581516,BAG 500g SWIRLY MARBLES,24,2011-12-09 11:26:00,0.39,14422,United Kingdom

In [43]:
df = df[df['Price'] > 0]

In [44]:
df["Revenue"] = df["Quantity"] * df["Price"]
df.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Revenue
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [45]:
df['CustomerID'] = df['CustomerID'].astype('str')

In [46]:
df.describe()

,Quantity,Date,Price,Revenue
count,519531.000000,519531,519531.000000,519531.000000
mean,10.398665,2011-07-04 16:05:04.485699584,3.887987,19.829120
min,1.000000,2010-12-01 08:26:00,0.001000,0.001000
25%,1.000000,2011-03-28 10:52:00,1.250000,3.750000
50%,3.000000,2011-07-20 11:55:00,2.080000,9.870000
75%,10.000000,2011-10-19 15:08:00,4.130000,17.400000
max,80995.000000,2011-12-09 12:50:00,13541.330000,168469.600000
std,157.007965,NaN,35.954733,272.865424

In [47]:
item_check = df.groupby("Itemname").agg(
    total_quantity=("Quantity","sum"),
    avg_price=("Price","mean"),
    transactions=("BillNo","count")
).reset_index()
item_check.sort_values("total_quantity", ascending=True)

,Itemname,total_quantity,avg_price,transactions
0,*Boombox Ipod Classic,1,16.980000,1
1240,FILIGREE DIAMANTE CHAIN,1,12.480000,1
1253,FIRE POLISHED GLASS NECKL GOLD,1,5.950000,1
1091,EASTER CRAFT IVY WREATH WITH CHICK,1,1.950000,1
3668,VINTAGE BEAD PINK JEWEL STAND,1,4.950000,1
...,...,...,...,...
3824,WHITE HANGING HEART T-LIGHT HOLDER,36523,3.226256,2265
1802,JUMBO BAG RED RETROSPOT,47998,2.491483,2084
3914,WORLD WAR 2 GLIDERS ASSTD DESIGNS,53799,0.321888,519
2036,MEDIUM CERAMIC TOP STORAGE JAR,77553,1.478306,242
2372,"PAPER CRAFT , LITTLE BIRDIE",80995,2.080000,1

In [48]:
item_check = df.groupby("Itemname").agg(
    total_quantity=("Quantity","sum"),
    avg_price=("Price","mean"),
    transactions=("BillNo","count")
).reset_index()
item_check.sort_values("total_quantity", ascending=True)

,Itemname,total_quantity,avg_price,transactions
0,*Boombox Ipod Classic,1,16.980000,1
1240,FILIGREE DIAMANTE CHAIN,1,12.480000,1
1253,FIRE POLISHED GLASS NECKL GOLD,1,5.950000,1
1091,EASTER CRAFT IVY WREATH WITH CHICK,1,1.950000,1
3668,VINTAGE BEAD PINK JEWEL STAND,1,4.950000,1
...,...,...,...,...
3824,WHITE HANGING HEART T-LIGHT HOLDER,36523,3.226256,2265
1802,JUMBO BAG RED RETROSPOT,47998,2.491483,2084
3914,WORLD WAR 2 GLIDERS ASSTD DESIGNS,53799,0.321888,519
2036,MEDIUM CERAMIC TOP STORAGE JAR,77553,1.478306,242
2372,"PAPER CRAFT , LITTLE BIRDIE",80995,2.080000,1

In [49]:
df.describe()

,Quantity,Date,Price,Revenue
count,519531.000000,519531,519531.000000,519531.000000
mean,10.398665,2011-07-04 16:05:04.485699584,3.887987,19.829120
min,1.000000,2010-12-01 08:26:00,0.001000,0.001000
25%,1.000000,2011-03-28 10:52:00,1.250000,3.750000
50%,3.000000,2011-07-20 11:55:00,2.080000,9.870000
75%,10.000000,2011-10-19 15:08:00,4.130000,17.400000
max,80995.000000,2011-12-09 12:50:00,13541.330000,168469.600000
std,157.007965,NaN,35.954733,272.865424

In [50]:
df.sort_values("Quantity", ascending=False).head(20)[
    ["BillNo","Itemname","Quantity","Price","CustomerID"]
]

,BillNo,Itemname,Quantity,Price,CustomerID
520583,581483,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446
59999,541431,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346
405138,573008,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,0.21,12901
198929,554868,SMALL POPCORN HOLDER,4300,0.72,13135
94245,544612,EMPIRE DESIGN ROSETTE,3906,0.82,18087
260928,560599,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,0.06,14609
51228,540815,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749
154834,550461,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749
416997,573995,SMALL CHINESE STYLE SCISSOR,3000,0.32,16308
280572,562439,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,12931
4853,536830,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,0.18,16754
194123,554272,PACK OF 60 PINK PAISLEY CAKE CASES,2700,0.42,12901
78472,543057,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,0.21,16333
405107,573003,RABBIT NIGHT LIGHT,2400,2.08,14646
85074,543669,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,0.94,16029
31774,539101,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,0.94,16029
88788,544152,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,2400,0.06,14609
120735,547037,PACK OF 12 SKULL TISSUES,2160,0.25,14101
420633,574294,RED HARMONICA IN BOX,2100,1.06,16333
492493,579498,RABBIT NIGHT LIGHT,2040,1.79,12798

In [51]:
df.loc[
    df["Itemname"] == "MEDIUM CERAMIC TOP STORAGE JAR",
    ["BillNo","Itemname","Quantity","Price","CustomerID"]
]

        BillNo                        Itemname  Quantity  Price CustomerID
59999   541431  MEDIUM CERAMIC TOP STORAGE JAR     74215   1.04      12346
180388  552882  MEDIUM CERAMIC TOP STORAGE JAR        96   1.04      14646
180810  552953  MEDIUM CERAMIC TOP STORAGE JAR         4   1.25      16745
181331  553005  MEDIUM CERAMIC TOP STORAGE JAR         5   1.25      14651
181481  553009  MEDIUM CERAMIC TOP STORAGE JAR         3   1.25      13601
...        ...                             ...       ...    ...        ...
514066  581108  MEDIUM CERAMIC TOP STORAGE JAR         2   1.25      15984
516549  581219  MEDIUM CERAMIC TOP STORAGE JAR         1   2.46      21774
519957  581439  MEDIUM CERAMIC TOP STORAGE JAR         2   2.46      21784
520463  581476  MEDIUM CERAMIC TOP STORAGE JAR        48   1.04      12433
521260  581492  MEDIUM CERAMIC TOP STORAGE JAR         2   2.46      21785

[242 rows x 5 columns]

In [52]:
df[df["CustomerID"] == '12346']

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Revenue
59999,541431,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom,77183.6

In [53]:
df = df[df["Quantity"] != 74215]

In [54]:
df.describe()

,Quantity,Date,Price,Revenue
count,519530.000000,519530,519530.000000,519530.000000
mean,10.255835,2011-07-04 16:05:32.300540416,3.887992,19.680594
min,1.000000,2010-12-01 08:26:00,0.001000,0.001000
25%,1.000000,2011-03-28 10:52:00,1.250000,3.750000
50%,3.000000,2011-07-20 11:55:00,2.080000,9.870000
75%,10.000000,2011-10-19 15:08:00,4.130000,17.400000
max,80995.000000,2011-12-09 12:50:00,13541.330000,168469.600000
std,118.544700,NaN,35.954768,250.987657

In [55]:
df.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Revenue
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [56]:
df.sort_values("Price", ascending=False).head(30)

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Revenue
14696,537632,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,18386,United Kingdom,13541.33
288772,A563185,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,20648,United Kingdom,11062.06
167329,551697,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,United Kingdom,8142.75
286674,562955,DOTCOM POSTAGE,1,2011-08-11 10:14:00,4505.17,20635,United Kingdom,4505.17
258372,560373,Manual,1,2011-07-18 12:30:00,4287.63,20407,United Kingdom,4287.63
405859,573080,Manual,1,2011-10-27 14:20:00,4161.06,12536,France,4161.06
405835,573077,Manual,1,2011-10-27 14:13:00,4161.06,12536,France,4161.06
390436,571751,Manual,1,2011-10-19 11:18:00,3949.32,12744,Singapore,3949.32
360367,569382,Manual,1,2011-10-03 16:44:00,3155.95,15502,United Kingdom,3155.95
334901,567353,Manual,1,2011-09-19 16:14:00,2653.95,20888,Hong Kong,2653.95
115387,546558,Manual,1,2011-03-15 09:50:00,2583.76,19096,Hong Kong,2583.76
286419,562946,Manual,1,2011-08-11 09:38:00,2500.00,15581,United Kingdom,2500.00
139672,548813,Manual,1,2011-04-04 13:03:00,2382.92,12744,Singapore,2382.92
474391,578149,DOTCOM POSTAGE,1,2011-11-23 11:11:00,2275.54,21600,United Kingdom,2275.54
505521,580610,DOTCOM POSTAGE,1,2011-12-05 11:48:00,2196.67,21733,United Kingdom,2196.67
390437,571751,Manual,1,2011-10-19 11:18:00,2118.74,12744,Singapore,2118.74
505763,580612,DOTCOM POSTAGE,1,2011-12-05 11:58:00,2114.00,21734,United Kingdom,2114.00
139675,548820,Manual,1,2011-04-04 13:04:00,2053.07,12744,Singapore,2053.07
330101,566927,Manual,1,2011-09-15 15:20:00,2033.10,17846,United Kingdom,2033.10
483307,578833,DOTCOM POSTAGE,1,2011-11-25 15:23:00,2028.25,21643,United Kingdom,2028.25
414711,573585,DOTCOM POSTAGE,1,2011-10-31 14:41:00,2019.05,21319,United Kingdom,2019.05
145238,549468,Manual,1,2011-04-08 14:27:00,1867.86,17940,United Kingdom,1867.86
513869,581023,DOTCOM POSTAGE,1,2011-12-07 10:35:00,1861.46,21752,United Kingdom,1861.46
521699,581498,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,21787,United Kingdom,1714.17
517534,581238,DOTCOM POSTAGE,1,2011-12-08 10:53:00,1683.75,21777,United Kingdom,1683.75
508679,580727,DOTCOM POSTAGE,1,2011-12-05 17:17:00,1599.26,14096,United Kingdom,1599.26
258732,560421,Manual,1,2011-07-18 15:13:00,1592.49,20421,United Kingdom,1592.49
317284,565847,DOTCOM POSTAGE,1,2011-09-07 12:44:00,1569.04,20799,United Kingdom,1569.04
490451,579297,DOTCOM POSTAGE,1,2011-11-29 11:23:00,1563.00,21659,United Kingdom,1563.00
453680,576644,DOTCOM POSTAGE,1,2011-11-16 10:01:00,1556.08,21509,United Kingdom,1556.08

In [57]:
items = df["Itemname"].dropna().unique()

# Lưu ra file txt
with open("item_names.txt", "w", encoding="utf-8") as f:
    for item in items:
        f.write(item + "\n")

print("Saved", len(items), "item names")

Saved 4006 item names

In [58]:
invalid_items = [
    "POSTAGE",
    "DOTCOM POSTAGE",
    "Manual",
    "Bank Charges",
    "Adjust bad debt",
    "AMAZON FEE"
]

df = df[~df["Itemname"].isin(invalid_items)]

In [59]:
df.describe()

,Quantity,Date,Price,Revenue
count,517425.000000,517425,517425.000000,517425.000000
mean,10.276417,2011-07-04 17:19:57.198202368,3.265879,19.037663
min,1.000000,2010-12-01 08:26:00,0.001000,0.001000
25%,1.000000,2011-03-28 11:34:00,1.250000,3.750000
50%,3.000000,2011-07-20 12:14:00,2.080000,9.840000
75%,10.000000,2011-10-19 15:29:00,4.130000,17.400000
max,80995.000000,2011-12-09 12:50:00,649.500000,168469.600000
std,118.738968,NaN,4.387178,248.958314

In [60]:
df.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Revenue
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [61]:
df.to_csv("Assignment-1_after_clean.csv", index=False)